[profile.default]
src = "src/contracts"
out = "out"
libs = ["lib"]
solc = "0.8.28"

# Optimizer settings
optimizer = true
optimizer_runs = 200

# Remappings
remappings = [
    "@semaphore/=../semaphore-contracts/contracts",
    "@semaphore-protocol/contracts/=node_modules/@semaphore-protocol/contracts/"
]

# See more config options at https://github.com/foundry-rs/foundry/tree/master/crates/config
